### ISSUE TITLE
Where are the pull requests?

### ISSUE THREAD

**Issue by stephenlauck** [VirtDev337/API-Server#2]
I didn't get to see any of your work as you did it. Better way to work is to commit the README.md as initial commit, then send me review requests as you work so we can discuss what's going on.

**Comment by VirtDev337** [comment]
I was setting up the repo and getting the base files together.   It took no time to put together the vm portion of the provision.sh, though I don't know I'll keep all of it and may add for Mac. 

All changes from here will be by branch and require review.   I wanted to have something for you to look at beyond the readme, most of which we have already discussed in session or in our one on one communication. 

The app.js is filler, for now,  and something I will need to discuss with you prior to work on it. 

I do not understand why there is a package.json and package_lock.json.  should both be in the repo?   

I will be creating issues myself for clarification on some of your instruction.

**Comment by stephenlauck** [comment]
It's actually very good practice to just check in the README and say what you are going to do. We call this "consumption driven development" where you create the documentation first and implement second.
